zkwasm testing script
near/wasmtime pull request #7
Opened 2023-09-22 10:51 UTC by MCJOHN974

(WIP)
Here I added script for easy run and test zkasm. Currently it need proverjs installed in same folder as wasmtime is. Further I will add automatic mode that downlads all necessary files (or maybe add some scripts from proverjs to this repo) for running zkwasm and proverjs preinstalled will not needed. Also will try to add this script to CI.

2023-09-22 11:10 UTC, nagisa approved these changes
Looks neat so far!

2023-09-22 14:38 UTC, MCJOHN974 commented
(WIP)
I tried to add some flags that will be useful in CI and in other usecases, but for now flags --install-zkwasm and --install-zkwasm-permanent don't work properly. Anyway, you still can use script without this flags with proverjs preinstalled, it should work.

2023-09-25 12:16 UTC, nagisa commented on cranelift/test-zk.sh
> +
One thing that I typically suggest doing is to `set -eux` and `set -o pipefail`. These provide a much better error handling and debugging opportunities in a black box environment like the CI.

2023-09-25 12:16 UTC, nagisa commented on cranelift/test-zk.sh
> +#!/bin/bash
```suggestion
#!/usr/bin/env bash
```

There are systems that don't store bash at `/bin` (e.g. NixOS.)

2023-09-25 16:34 UTC, MCJOHN974 commented
Hey, @nagisa , I changed bash script a bit and also added this script to CI. As you can see [job](https://github.com/near/wasmtime/actions/runs/6301925196/job/17108045776) runs succesfully, and, [job](https://github.com/near/wasmtime/actions/runs/6301792507/job/17107623262) fails cause of error in add_memory.zkwasm.

2023-09-25 16:34 UTC, akashin requested changes
Looks super useful, thanks!

2023-09-25 16:34 UTC, akashin commented on .github/workflows/main.yml
> +    - run: ls
Looks like can this be removed?

2023-09-25 16:34 UTC, akashin commented on .github/workflows/main.yml
> +        submodules: true
Technically, we don't really need submodules, as we don't build Rust code in this action.

2023-09-25 16:34 UTC, akashin commented on .github/workflows/main.yml
> +    name: Test generated zkwasm
Nit: "zkwasm" -> "zkAsm"

2023-09-25 16:34 UTC, akashin commented on .github/workflows/main.yml
> +  Runzk:
Maybe a bit more specific "test_zkasm"?

2023-09-25 16:34 UTC, akashin commented on ci/test-zk.sh
> +    zkasm_file="${zkasm_file//\/\//\/}"
Why do we need this?

2023-09-25 16:34 UTC, akashin commented on ci/test-zk.sh
> +        npm install
Consider using https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable here

2023-09-25 16:34 UTC, akashin commented on ci/test-zk.sh
> +    "temporary")
I don't think we would ever use this mode, both in local and remote context, should we remove it?

2023-09-25 16:43 UTC, akashin commented on ci/test-zk.sh
> +RED='\033[0;31m'
These are not used anymore

2023-09-26 10:26 UTC, nagisa commented on .github/workflows/main.yml
> +  Runzk:
The comment above is also wrong now.

2023-09-26 11:08 UTC, MCJOHN974 commented
Hey, @akashin, @nagisa I made some cleanup and the workflow runs as expected. Also i fixed all comments except [this one](https://github.com/near/wasmtime/pull/7#discussion_r1336136868), but I think it is an enchantment and can be added later

2023-09-26 11:56 UTC, akashin approved these changes
Looks good, let's ship it!

2023-09-26 12:01 UTC, MCJOHN974 commented
Thanks all for your reviews!

2023-09-26 13:59 UTC, merged